/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.collabnote.client;

import com.collabnote.client.ui.MainFrame;
import com.collabnote.client.viewmodel.TextEditorViewModel;

import java.awt.EventQueue;

public class App {
    private MainFrame frame;

    public App(boolean visible) {
        if (visible)
            EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    frame = new MainFrame();
                    frame.setVisible(visible);
                }
            });
        else
            frame = new MainFrame();
    }

    public static void main(String[] args) {
        new App(true);
    }

    public TextEditorViewModel getViewModel() {
        return this.frame.getViewModel();
    }
}
